version: '3.8'

services:
  postgres:
    image: postgres
    container_name: petcontrol-postgres
    environment:
      POSTGRES_USER: 1234
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: PetControlSystem
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
